version: '3'
services:
    smac-back:
        build: .
        container_name: smac-back_c
        env_file:
            - .env
        ports:
            - '3000:3000'
        volumes:
            - .:/app
            - /app/node_modules
